# Generated by Django 4.0 on 2021-12-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headline_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='image',
        ),
    ]
