# Generated by Django 4.0 on 2021-12-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_headline_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='website',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
    ]
