# Generated by Django 4.0 on 2021-12-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_headline_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
