# Generated by Django 4.0 on 2021-12-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
