# Generated by Django 4.0 on 2021-12-31 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_website_delete_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
